AWSTemplateFormatVersion: '2010-09-09'
Description: create group whose members can read/write Terraform state and create  resources (via Terraform) in aws resource accounts 

Parameters:
  GroupName:
    Type: String
  BackendRole:
    Type: String
  AssumePolicy:
    Type: String
  UserDataPolicy:
    Type: String
  TrustedAccountId:
    Type: String
  LogAccountId:
    Type: String

Rules: 
  Deployment:
    Assertions:
      - Assert: !Equals 
        - !Ref AWS::AccountId
        - !Ref TrustedAccountId
        AssertDescription: 'deployed in account that needs to access operational resources'

Resources:
  Group:
    Type: AWS::IAM::Group
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      GroupName: !Ref GroupName
      ManagedPolicyArns:   
        - !Ref AssumeRolePolicy
        - !Ref ManagedUserInfoPolicy
  AssumeRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      ManagedPolicyName: !Ref AssumePolicy
      Description: !Sub "group members can assume ${BackendRole}"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: !Sub "Assume${BackendRole}"
            Effect: Allow 
            Action: 
              - 'sts:AssumeRole'
            Resource:
              - !Sub "arn:aws:iam::${LogAccountId}:role/${BackendRole}"
  ManagedUserInfoPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      ManagedPolicyName: !Ref UserDataPolicy
      Description: group members can manage their iam information
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowUserToVieWGeneralInfo
            Effect: Allow
            Action: 
              - 'iam:GetGroupPolicy'
              - 'iam:ListGroupPolicies'
              - 'iam:ListAttachedUserPolicies'
              - 'iam:ListAttachedGroupPolicies'
            Resource: '*'
          
          - Sid: AllowUserToViewRelevantRoles #doesn't work 4 crossAccountAccess
            Effect: Allow
            Action: 
              - 'iam:GetRole'
            Resource: 
              - !Sub "arn:aws:iam::${LogAccountId}:role/${BackendRole}"

          - Sid: AllowUserToViewGroupMemberships
            Effect: Allow
            Action:
              - 'iam:ListGroupsForUser'
            Resource:
              - !Join 
                - ''
                - - !Sub "arn:aws:iam::${TrustedAccountId}:user/"
                  - '${aws:username}'

          - Sid: AllowUserToManagePersonalMFA
            Effect: Allow 
            Action: 
              - 'iam:ListMFADevices'
              - 'iam:ResyncMFADevice'
            Resource:
              - !Join
                - ''
                - - !Sub "arn:aws:iam::${TrustedAccountId}:user/"
                  - '${aws:username}' 

          - Sid: AllowUserToViewPersonalInfo
            Effect: Allow
            Action: 
              - 'iam:GetUser'
              - 'iam:ListUserPolicies'
            Resource:
              - !Join
                - ''
                - - !Sub "arn:aws:iam::${TrustedAccountId}:user/"
                  - '${aws:username}'
