AWSTemplateFormatVersion: '2010-09-09'
Description: create group whose members can run terraform commands

Parameters:
  PowerUserPolicyArn:
    Type: String
    Description: can be an empty string therefore is an optional parameter
  GroupName:
    Type: String
  TfStateRoleName:
    Type: String
  GroupPolicyName:
    Type: String
  ResourceAccessorAccountId:
    Type: String
  OperationalResourcesAccountId:
    Type: String


Conditions: 
  PowerUserPolicyArnIsEmpty: !Equals ["", !Ref PowerUserPolicyArn]
  PermitEmptyPowerUserPolicyArn: !Not [!Equals ["", !Ref PowerUserPolicyArn]]



Rules: 
  Deployment:
    Assertions:
      - Assert: !Equals 
        - !Ref AWS::AccountId
        - !Ref ResourceAccessorAccountId
        AssertDescription: 'deployed in account that needs to access operational resources'


Resources:
  Group:
    Type: AWS::IAM::Group
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      GroupName: !Ref GroupName
      ManagedPolicyArns: 
        - Fn::If:
          - PowerUserPolicyArnIsEmpty
          - !Ref 'AWS::NoValue'
          - !Ref PowerUserPolicyArn       
        - !Ref GroupPolicy
  GroupPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      ManagedPolicyName: !Ref GroupPolicyName 
      Description: !Sub "grants READ/WRITE permissions to terraform operational resources by assuming ${TfStateRoleName}"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ReadWriteAccessToTerraformStateFiles
            Effect: Allow 
            Action: 
              - 'sts:AssumeRole'
            Resource:
              - !Sub "arn:aws:iam::${OperationalResourcesAccountId}:role/${TfStateRoleName}"   
