AWSTemplateFormatVersion: '2010-09-09'
Description: create users permitted to run terraform commands

Parameters: 
  Username:
    Type: String  
  UserGroup:
    Type: String
  ResourceAccessorAccountId:
    Type: String
  UserTagKey:
    Type: String
  ValueOfUserTag:
    Type: String
  Setup: 
    Type: String

Conditions: 
  isSingleAccountSetup: !Equals ["single", !Ref Setup]
  isMultiAccountSetup: !Equals ["multiple", !Ref Setup] 


Rules:
  Deployment:
    Assertions:
      - Assert: !Equals
        - !Ref AWS::AccountId
        - !Ref ResourceAccessorAccountId
        AssertDescription: 'deployed in account where users are managed'


Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      Groups: 
        - !Ref UserGroup
      UserName: !Ref Username
      Tags:
        - Key: !Ref UserTagKey
          Value: !Ref ValueOfUserTag

Outputs:
  SingleAccountSetupUserArn:
    Condition: isSingleAccountSetup    
    Description: arn for user
    Value: !GetAtt User.Arn
    Export:
      Name: SnglUserArn

  MultiAccountSetupUserArn:
    Condition: isMultiAccountSetup    
    Description: arn for user
    Value: !GetAtt User.Arn
    Export:
      Name: MultiUserArn