AWSTemplateFormatVersion: '2010-09-09'
Description: creates a role in a workload account that users need to assume to create resourcs, via terraform, in the workload account


Parameters:
  MaxSession:
    Type: String
  UserTagValue:
    Type: String
  WorkloadRoleName:
    Type: String
  WorkloadAccountId:
    Type: String
  ResourceAccessorAccountId:
    Type: String


Rules:
  Deployment:
    Assertions:
      - Assert: !Equals
        - !Ref AWS::AccountId
        - !Ref WorkloadAccountId 
        AssertDescription: 'must be deployed in a workload account'

Resources:
  Role:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain 
    Properties:
      RoleName: !Ref WorkloadRoleName
      Description: assume role to create resources via terraform
      MaxSessionDuration: !Ref MaxSession
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow 
            Principal:
              AWS: !Ref ResourceAccessorAccountId # Trusted Account
            Action: 
              - 'sts:AssumeRole'
            Condition: 
              Bool: 
                aws:MultiFactorAuthPresent: true
              StringEquals: 
                aws:PrincipalType: 
                  - 'User'
              StringLike: 
                aws:PrincipalTag/Terraformers:
                  - !Ref UserTagValue
                sts:RoleSessionName: 
                  - '${aws:username}'