AWSTemplateFormatVersion: '2010-09-09'
Description: creates a role in a workload account that users need to assume in order to create resourcs, via terraform, within the workload account


Parameters:
  WorkloadAccountId:
    Type: String
  ResourceAccessorAccountId:
    Type: String
  TfStateRoleName:
    Type: String
  MaxSession:
    Type: String
  ValueOfUserTag:
    Type: String


Rules:
  Deployment:
    Assertions:
      - Assert: !Equals
        - !Ref AWS::AccountId
        - !Ref WorkloadAccountId 
        AssertDescription: 'must be deployed in trusting account'

Resources:
  Role:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain 
    Properties:
      RoleName: !Ref TfStateRoleName
      Description: assume role to create resources via terraform
      MaxSessionDuration: !Ref MaxSession
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow 
            Principal:
              AWS: !Ref ResourceAccessorAccountId # Trusted Account
            Action: 
              - 'sts:AssumeRole'
            Condition: 
              Bool: 
                aws:MultiFactorAuthPresent: true
              StringEquals: 
                aws:PrincipalType: 
                  - 'User'
              StringLike: 
                aws:PrincipalTag/Terraformers:
                  - !Ref ValueOfUserTag
                sts:RoleSessionName: 
                  - '${aws:username}'