---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Terraform related group and policies
Metadata: 
  AWS::Cloudformation::Interface: 
    ParameterGroups: 
      - Label: 
          default: create groups and policies in this account
        Parameters: 
          - GroupName
          - TrustedAccount
      - Label: 
          default: contains resources and role
        Parameters: 
          - TrustingAccount
          - BackendRoleName
Parameters: 
  GroupName:
    Type: String
    Description: | 
      name of group allowed to run terraform actions  
  TrustedAccount:
    Type: String
    Description: |
      users in this account are able to assume 
      terraformbackend role in trusting account
  TrustingAccount:
    Type: String
    Description: |
      contains terraform backend resources
      and role that users in trusted account 
      need to assume in order to access the 
      terraform backend resources 
  BackendRoleName: 
    Type: String
    Description: | 
      name of terraform backend role in Trustint
      Account that is assumable by users in Trusted
      Account who have the correct tag key and value 
Rules: 
  EnsureDeployingToCorrectAccount: 
    Assertions: 
      - Assert: !Equals 
          - !Ref AWS::AccountId
          - !Ref TrustedAccount
        AssertDescription: 'Stack can only be deployed into the specified aws account'  

Resources: 
  #############################################
  # create group for terraform admins         #
  # - users in this group are able to read    #
  #   from and write to terraform state files #
  #############################################
  Group: 
    Type: 'AWS::IAM::Group'
    Properties: 
      GroupName: !Sub "${GroupName}"
      ManagedPolicyArns: 
        - !Ref PolicyForTerraformBackendRole
  
  #######################################################
  # create terraform admin policy                       #
  # - grants permission to assume TerraformBackend Role #
  #######################################################
  PolicyForTerraformBackendRole: 
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: AssumeTerraformBackendPolicy
      Description: grant permission to assume TerraformBackendRole in TerraformBackend Account
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Sid: AssumeTerraformBackendRole
            Effect: Allow
            Action: 
              - 'sts:AssumeRole'
            Resource: 
              # make sure this role exists in the trusting account
              - !Sub "arn:aws:iam::${TrustingAccount}:role/terraform/${BackendRoleName}"        